### ISSUE TITLE
How to add leaves model?

### ISSUE THREAD

**Issue by Roy2xc** [tudelft3d/adtree#12]
Hello,
If I want to add a ply/obj  file as the leaves model, which part of codes should I modify?
Thank you!

**Comment by Roy2xc** [comment]
I'm new in 3D reconstruction, could you please give me some hits, thank you very much!

**Comment by LiangliangNan** [comment]
The code is here:
https://github.com/tudelft3d/AdTree/blob/e621d7154d578d97ea666ff63d19faf1ab1fbf3d/AdTree/tree_viewer.cpp#L483
It generates a set of leaves represented as a separate mesh model (that you can export as an obj file).

**Comment by Roy2xc** [comment]
Thank you so much!
