### ISSUE TITLE
Cannot Open Input File

### ISSUE THREAD

**Issue by jhr990206** [tudelft3d/AdTree#13]
Hello,
I have a problem when I run the project with Microsoft Visual Studio 2019，it shows that cannot open input file "3rd_imgui.lib". But I don't find any ".lib" file in the project.
could you tell me how to fix it? thank you!

**Comment by LiangliangNan** [comment]
VS2019 should not ask for that lib. Can you please describe how you opened the project using VS2019?
Besides, I assume any user who builds AdTree from the source code has experience with C++ programming and is familiar with the tools (e.g.,  CMake and the development environment) used.

**Comment by jhr990206** [comment]
Thank you for your reply!
As the picture shows, I have used cmake-gui to open the project. Then I opened the project using VS2019 and tried to run, and it turned out that to be the problem.




淡墨、流年丿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tudelft3d/AdTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tudelft3d/AdTree] Cannot Open Input File (Issue #13)





 
VS2019 should not ask for that lib. Can you please describe how you opened the project using VS2019?
 Besides, I assume any user who builds AdTree from the source code has experience with C++ programming and is familiar with the tools (e.g.,  CMake and the development environment) used.

**Comment by LiangliangNan** [comment]
The pictures were missed?
Does it happen during the configure step, generation step, compiling, or linking step?
Please describe your operation in a way such that I may be able to reproduce your issue.

**Comment by jhr990206** [comment]
Sorry! I forgot to send you the picture.
Here the picture is.




淡墨、流年丿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tudelft3d/AdTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tudelft3d/AdTree] Cannot Open Input File (Issue #13)





 
The pictures were missed?
 Does it happen during the configure step, generation step, compiling, or linking step?
 Please describe your operation in a way such that I may be able to reproduce your issue.

**Comment by LiangliangNan** [comment]
I really want to help, but unfortunately, you don't provide any input and I don't understand what you are asking.
Some suggestions:
http://www.catb.org/~esr/faqs/smart-questions.html
