### ISSUE TITLE
How to build AdTree using CMake?

### ISSUE THREAD

**Issue by jhr990206** [tudelft3d/AdTree#14]
Hello,
I'm sorry I forgot to upload the picture last week. 
First,  I configured and generated the project with cmake-gui, as shown in the picture named "cmake". Then I opened the project and ran it with VS2019. As a result I got a problem, it showed that cannot open input file "3rd_imgui.lib", as shown in the picture named "problem". And I didn't modify the linker's additional library directory in the project properties because I didn't find any “.libs” files.
could you tell me how to fix it? thank you!
![cmake](https://user-images.githubusercontent.com/96403122/192934648-515a51e5-fd3a-4045-af04-45e313801c0c.PNG)
![problem](https://user-images.githubusercontent.com/96403122/192934665-d22309bd-296f-4e0d-89cb-b00345ec7d87.PNG)

**Comment by LiangliangNan** [comment]
Only the error message doesn't give any useful information for figurimg out the issue. Please post your entire CMake log file, and the Visual Studio log file (that logged the compiling and linking processes).

**Comment by LiangliangNan** [comment]
How did you actually "Open" the project in Visual Studio? 
I guess you might have opened the 'AdTree.vcxproj' file. But this is not correct, you should open the solution file, e.g., 'AdTree.sln'. See the build directory generated by CMake.
![image](https://user-images.githubusercontent.com/15526536/192987808-43b12e5a-42bd-4521-8f0d-06e9d6bdcca9.png)

**Comment by jhr990206** [comment]
Thanks for your reply!
I did open the 'AdTree.sln' file first, as shown in the picture, and clicked on 'Open Project' to open the project. 
Also, I don't know how to find the CMake log file, or the Visual Studio log file you said.
![cmake](https://user-images.githubusercontent.com/96403122/192990547-de9e741e-4c0f-4268-b23c-5dee4d325b13.PNG)

**Comment by LiangliangNan** [comment]
In the "Where the source code:", you should point to the ROOT directory of the whole project.

**Comment by jhr990206** [comment]
Sorry, I still can't find the file. The root directory of my project is like this, there is no "Where the source code:" like you said.
![image](https://user-images.githubusercontent.com/96403122/193009530-d4a516c5-ea87-4bb2-b8b3-4616bf58387a.PNG)

**Comment by LiangliangNan** [comment]
That is what CMake asked for. See your CMake interface (where you specify the source path).
