### ISSUE TITLE
Prebuild Usecase

### ISSUE THREAD

**Issue by par45ite** [tudelft3d/AdTree#17]
Hello, 

first of all thank you for providing your software. 
Since I unfortunately have no idea of programming, but still would like to try your application, a question: 

Since you provided a prebuild for version 1.1.0, can I just run it like a normal application on Windows? Could I thus process a point cloud and transfer it as a 3D object for further processing in e.g. Rhino3D? 

For version 1.1.1 you have only provided the source code. Unfortunately I have absolutely no idea how I could build this manually (despite instructions). 

Would version 1.1.0 be sufficient for my purposes to use trees as 3D objects for further processing in Rhino 3D, or are programming skills required even here? 
And what kind of point cloud data is reqired for AdTree? 

Greetings, 
Ludwig

**Comment by LiangliangNan** [comment]
The results from 1.1.0 and 1.1.1 are the same (only minor changes in lib names and log messages are affected).
Please try 1.1.0 first and then let me how it works.
I also believe it is possible to build it from the source code even without programming skills. Just follow the command line instructions.

**Comment by par45ite** [comment]
Thanks for quick response!

1.1.0 seems to work very well for my pointclouds.
I will perform further tests.
