### ISSUE TITLE
Batch Skeleton Export [Feature Request]

### ISSUE THREAD

**Issue by harry1576** [tudelft3d/AdTree#18]
Hi there,

The batch processing is very useful - thanks for adding. I was just wondering would it be possible that this could also support the exporting of the skeletons? Rather than just the meshes?

Cheers,
Harry

**Comment by LiangliangNan** [comment]
Hi, thanks for the feature request.
It has been implemented, and you can grab the latest code and build it from the source code.
Pre-built binaries are also available here (Windows and Mac. I don't have a Linux machine for the moment): https://github.com/tudelft3d/AdTree/releases/tag/v1.1.2
