### ISSUE TITLE
Airborne point clouds

### ISSUE THREAD

**Issue by ayoubOUSSM2021** [tudelft3d/AdTree#19]
Hello, please may I know if I can use AdTree to model airborne point clouds (vegetation) or do I need to have a terrestrial point cloud? Thank you in advance.

**Comment by LiangliangNan** [comment]
Your question can already be ansered by simply trying the method :-)
And you will see:
  - if the data is relatively compelte (i.e., the main branch is captured), you get a plausible 3D model;
  - if the main branch is completely missing, you will get something nonsense.
