### ISSUE TITLE
Unable to run the prebuilt windows Adtree.exe v1.12

### ISSUE THREAD

**Issue by Robonus** [tudelft3d/AdTree#20]
![image](https://user-images.githubusercontent.com/107359003/223105770-a0f93a67-27ba-46d0-9000-11c106cb1766.png)
![image](https://user-images.githubusercontent.com/107359003/223105847-9691562d-f406-4622-955e-5cc1dd8948e2.png)

Hi.

I'm really amazed by what your program can do, however i can't seem to get the (prebuilt) Adtree.exe (v1.12 for windows) to work.
I've tried to install the VC-redist.x64.exe but i get an error message saying i'v allready got a newer version installed.

Any idea's to what i can try to make the prebuilt exe work?

Kind regards,
Robin

**Comment by LiangliangNan** [comment]
Hi, the issue might be cause by one of the following:
- AdTree is run through remote desktop. If so, try to run it locally.
- Your machine/laptop has two GPUs (one integrated and one discrete), and only the integrated GPU is accessible but it doesn’t support OpenGL 3.2. If so, try to allow the use of the discrete GPU.
- Your machine/laptop only has an integrated GPU that doesn’t support OpenGL 3.2. If so, try another machine.

Let me know if all of the above cannot solve the issue.

**Comment by Robonus** [comment]
Hi Liang,
thank you for the suggestions. I'm trying to run it on a standalone laptop. I've tried it on 2 laptops, one on windows 10 (i7, GPU Quadro P2000), one on windows 11 (i7 RTX2070). I keep getting the same errors on both laptops. Both laptops have the latest GPU drivers.

I have a newer version of the VC-redist.x64. That doesn't seem like a problem right?
![image](https://user-images.githubusercontent.com/107359003/223216435-ece1cd36-d5a2-4aec-aaf3-cbfb472f8913.png)

**Comment by LiangliangNan** [comment]
What is your GPU?

**Comment by Robonus** [comment]
You are a true wizard my friend, that's done the job. 
Will try some pointclouds tomorrow.

Thanks a lot for the quick replying.

**Comment by JinyuanShao** [comment]
Hi, thanks for very great work!

I was trying to run the prebuild v1.12 but met the same problem. I first change set the discrete GPU to run the exe and the first error had been solved.

However, I'm stuck a new error: `GLFW error 65542: WGL: The driver does not appear to support OpenGL`

I was trying to update my graphic driver for the dsicrete GPU but it's still not working.

Could you let me know how to solve this problem? My GPU is NVIDIA RTX 3070 desktop, by the way.

**Comment by LiangliangNan** [comment]
Have you tried this: https://www.intel.com/content/www/us/en/support/articles/000087403/intel-nuc.html
How did you make sure the discrete GPU (instead of the integrated one) was used?

**Comment by JinyuanShao** [comment]
> Have you tried this: https://www.intel.com/content/www/us/en/support/articles/000087403/intel-nuc.html How did you make sure the discrete GPU (instead of the integrated one) was used?

Yes, I set graphics setting as below:
![image](https://github.com/tudelft3d/AdTree/assets/37828195/da6926a7-7b59-43c8-b7c4-024a20d3d1cd)
Then I set NVIDIA the like this:
![image](https://github.com/tudelft3d/AdTree/assets/37828195/3ad77d93-f240-48b3-ac5d-381206cd8a54)

Did I miss something?

**Comment by JinyuanShao** [comment]
> I am not sure if you need to restart your laptop for the changes to take effect. Maybe you can give it a try? I also assume you're running on 64-bit Windows.
> 
> If it still doesn't work, please try to build it from the source code.

I've tried restarting. And yes, I'm using the 64-bit machine.

It seems like still not working. I'll try to build from the source.

Thank you very much, though.
