### ISSUE TITLE
Code running problems in WLS

### ISSUE THREAD

**Issue by than2** [tudelft3d/AdTree#21]
Hi Liang,

Let you after I successfully compailed Adtree in my window linux subsystem, I run the code as you mentioned in the read.me file.

I get the error like this, do you know any solutions for this problem?
![error](https://user-images.githubusercontent.com/48503256/233130974-21f6a84d-8fb4-4c0b-ad57-567a4350086e.png)

best,
Tao

**Comment by LiangliangNan** [comment]
You should have found the binary file by simply exploring those folders :-)
It is located in `Release/bin`

**Comment by than2** [comment]
I got it, thanks, liang, you are super helpful, I just missed the `bin` file.
