### ISSUE TITLE
Chinese cannot be displayed

### ISSUE THREAD

**Issue by jhr990206** [tudelft3d/AdTree#23]
Hello!

The code in the picture comes from the file "viewer_imgui.cpp". I tried to modify the content in Text to Chinese, but what was displayed “?”, Chinese cannot be displayed. Can you provide me with a solution? Thank you!
![picture](https://github.com/tudelft3d/AdTree/assets/96403122/4f93bfed-ef0e-4a70-9ed4-5aa5f3e3f71f)

**Comment by LiangliangNan** [comment]
In line 97 of "viewer_imgui.cpp", you see
```c++ 
io.Fonts->AddFontFromMemoryCompressedTTF(droid_sans_compressed_data, droid_sans_compressed_size, static_cast<float>(font_size * dpi_scaling()));
```
Here the font "droid_sans_compressed_data" doesn't support Chinese.

You will first need to add a font that supports Chinese, e.g.,
```c++ 
io.Fonts->AddFontFromFileTTF("/Users/lnan/Documents/Projects/Easy3D/resources/fonts/cn_Mao.ttf", static_cast<float>(font_size * dpi_scaling()), nullptr, io.Fonts->GetGlyphRangesChineseSimplifiedCommon());
```

Then input your Chinese characters like: 
```c++ 
(const char*)u8"你好".
```

Below is what I just got:
<img width="297" alt="Screen Shot 2023-12-28 at 23 08 17" src="https://github.com/tudelft3d/AdTree/assets/15526536/d81b4248-78d3-4c7c-afb7-ddea09cd4547">

**Comment by jhr990206** [comment]
Thank you for your guidance. However, after I made the changes according to your code, The font was successfully modified，but the Chinese still cannot be displayed, as shown in the following picture, which was very confusing for me. I hope to receive your guidance again, thank you very much!


The modified code is as follows:


&nbsp; &nbsp; void ViewerImGui::reload_font(int font_size)
	{
		ImGuiIO&amp; io = ImGui::GetIO();
		io.Fonts-&gt;Clear();
&nbsp; &nbsp; &nbsp; &nbsp; /*io.Fonts-&gt;AddFontFromMemoryCompressedTTF(droid_sans_compressed_data, droid_sans_compressed_size, static_cast<float&gt;(font_size * dpi_scaling()));*/
&nbsp; &nbsp; &nbsp; &nbsp; io.Fonts-&gt;AddFontFromFileTTF("C:/Users/23599/Desktop/Easy3D/Easy3D-main/resources/fonts/cn_毛泽东.ttf", static_cast<float&gt;(font_size * dpi_scaling()), nullptr, io.Fonts-&gt;GetGlyphRangesChineseSimplifiedCommon());
&nbsp; &nbsp; &nbsp; &nbsp; io.FontGlobalScale = static_cast<float&gt;(1.0 / pixel_ratio());
&nbsp; &nbsp; &nbsp; &nbsp; ImGui_ImplOpenGL3_DestroyDeviceObjects();
	}










止水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tudelft3d/AdTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月29日(星期五) 上午6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tudelft3d/AdTree] Chinese cannot be displayed (Issue #23)





 
In line 97 of "viewer_imgui.cpp", you see
 io.Fonts-&gt;AddFontFromMemoryCompressedTTF(droid_sans_compressed_data, droid_sans_compressed_size, static_cast<float&gt;(font_size * dpi_scaling()));
 
Here the font "droid_sans_compressed_data" doesn't support Chinese.
 
You will first need to add a font that supports Chinese, e.g.,
 io.Fonts-&gt;AddFontFromFileTTF("/Users/lnan/Documents/Projects/Easy3D/resources/fonts/cn_Mao.ttf", static_cast<float&gt;(font_size * dpi_scaling()), nullptr, io.Fonts-&gt;GetGlyphRangesChineseSimplifiedCommon());
 
Then input your Chinese characters like:
 (const char*)u8"你好".
 
Below is what I just got:
 Screen.Shot.2023-12-28.at.23.08.17.png (view on web)

**Comment by LiangliangNan** [comment]
Please format your code (I couldn't read it), and the image is also not attached.

**Comment by LiangliangNan** [comment]
See the following comment in 'viewer_imgui.cpp':     
```C++
// If you want to show other languages, e.g., Chinese, you first need to use a TTF font file that supports Chinese. You can replace the above line by:
 io.Fonts->AddFontFromFileTTF("/Users/lnan/Documents/Projects/Easy3D/resources/fonts/cn_Mao.ttf", static_cast<float>(font_size * dpi_scaling()), nullptr, io.Fonts->GetGlyphRangesChineseSimplifiedCommon());
// Then input the Chinese characters like: 
(const char*)u8"你好". 
```

**Comment by LiangliangNan** [comment]
I will reply here (Please don't create another issue).
As I have shown you before, the code can already visualize Chinese characters. 
Please do:
 -) show your code of "AddFontFromFileTTF(...)";
 -) make sure your font file supports Chinese. You can send me your file so I can check.
 -) make sure your font file has been successfully loaded.

**Comment by jhr990206** [comment]
This file has been mod
[code.txt](https://github.com/tudelft3d/AdTree/files/14264972/code.txt)
ified based on your code. I hope you can help me check for any issues. Thank you very much!

**Comment by LiangliangNan** [comment]
Can you try to change (in both the folder where you store the ttf file and your code) your font file from `cn_毛泽东.ttf` to `cn_Mao.ttf`?
I suspect either your IDE, or the code, or your OS doesn't support Chinese characters in the path string.
Let me know if this solves the problem.

**Comment by jhr990206** [comment]
The problem has been resolved! Thank you very much for helping me solve the problem!&nbsp;


止水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liangliang ***@***.***&gt;; 
发送时间: 2024年2月13日(星期二) 晚上11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tudelft3d/AdTree] Chinese cannot be displayed (Issue #23)






你能试着改变你的字体文件（在你存放ttf文件和你的代码的文件夹中）吗？cn_毛泽东.ttf到cn_Mao.ttf?
我怀疑你的IDE，或者代码，或者你的操作系统不支持路径字符串中的中文字符。
让我知道这是否解决了问题。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< tudelft3d / AdTree /议题/ 23 / ***@***.***和&gt;

**Comment by LiangliangNan** [comment]
Was it due to the Chinese title of the font file?

**Comment by jhr990206** [comment]
That's right, that's the reason.
