### ISSUE TITLE
Support export manifold mesh

### ISSUE THREAD

**Issue by HowcanoeWang** [tudelft3d/AdTree#24]
Thanks a lot for making such a good tool to extract the tree skeleton and mesh, it works perfect on our data.

But when analyzing the mesh, I found there are several inner and intersections among each branches. This is not convenicence for the Volume calculation.

I have tried several tools like Blender and CloudCompare to fixing this "non-manifold" problem but failed. I am wondering if it can be fixed at the data source, whether AdTree can export the clean up meshes directly.

PS: the manifold mesh means, the mesh model only has the skin surface without holes or any faces inside the object.

**Comment by LiangliangNan** [comment]
In the current implementation, each branch is separately extracted from the fitted spline curves, and thus branches typically intersect at the joints. Seamlessly stitching the branches in principle is possible by computing the intersections of two generalized cylinders. But this requires to handle a few special cases,  which is quite tedious. This is apparently less relevant to our research, so we leave this to the users of AdTree as postprocessing (and thus we may not implement it in this software prototype). However, I can suggest a workaround:
 - step 1: obtain closed surface meshes for each branch, by simply filling the holes at the two end points of the branch (In the result of AdTree, each branch is a connected component. So you need to loop over all branches).
 - step 2:  compute the union of all the comments. This will result in a closed and manifold mesh representation of the tree branch structure, from which the volume could be easily computed.

Hope this helps.

**Comment by HowcanoeWang** [comment]
Thanks a lot for your kindly reply, I will try this postprocessing as you suggested!
