### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by LANXIAODDD** [tudelft3d/AdTree#25]
您好！

我在Windows10 vscode 下编译代码出现错误：
![Snipaste_2024-02-01_17-13-10](https://github.com/tudelft3d/AdTree/assets/79525202/9fb3bc4a-1a3d-43ff-ad39-bfb4c4424ca3)

请问如何解决

**Comment by LiangliangNan** [comment]
从你的log截图来看，你的系统不是Windows，而是某种Linux。
请告知你的系统是什么，用的什么编译器？

**Comment by LANXIAODDD** [comment]
win10的操作系统
![image](https://github.com/tudelft3d/AdTree/assets/79525202/64cf968f-b53b-4f64-9b2b-b254066b5027)
编译器mingw64 g++

**Comment by LiangliangNan** [comment]
原生windows下的静态库扩展都是.lib. Windows下目前支持微软的编译器，你用Visual Studio试试。

**Comment by LANXIAODDD** [comment]
好的，谢谢

**Comment by LANXIAODDD** [comment]
使用VS解决了问题，感谢！

**Comment by LANXIAODDD** [comment]
顺便问一下，输入数据指的是去除叶子点云后的数据吗

**Comment by LiangliangNan** [comment]
可以包含叶子。你可以比较一下，输入有/没有叶子对重建结果的影响。

**Comment by LiangliangNan** [comment]
@LANXIAODDD 我对项目配置做了改进，现在Windows下应该也支持MinGW了（也就是你之前的vscode 编译）。代码在“dev”（不是“main”），你试试看行不行。有结果请告诉我一声

**Comment by LANXIAODDD** [comment]
您好，
感谢，现在vscode可以正常编译了！
![image](https://github.com/tudelft3d/AdTree/assets/79525202/2be0bea6-8b05-415a-8b18-1ceeceb42c93)

但是在编译过程中，由于mingw gcc 缺少这个类，直接进行编译的话，会出现报错：
![image](https://github.com/tudelft3d/AdTree/assets/79525202/1e85e7d4-1388-44a4-b420-74016e12a78c)
解决方案：https://github.com/meganz/mingw-std-threads

**Comment by LiangliangNan** [comment]
I am confused. You firstly show a snapshot of a successful build, but then another one with error. What are the differences between the two?

**Comment by LANXIAODDD** [comment]
在我的电脑上。用您新配置的项目构建可执行程序的过程中，首先会出现编译报错（如上图2），解决后，即可编译成功（如上图1）。

**Comment by LiangliangNan** [comment]
很高兴问题已解决。
Good luck to your project！
