### ISSUE TITLE
Generate mesh by L-system grammar

### ISSUE THREAD

**Issue by Junang-Wang** [tudelft3d/AdTree#28]
Hi there,

I am currently working on a 3D reconstruction project involving the mapping of L-system to 3D mesh. I am wondering if it's possible to implement AdTree to generate synthetic trees directly using L-system strings instead of inputting point clouds. If it is possible, could you please provide guidance on how to implement it?

Thank you in advance,

JunAng

**Comment by LiangliangNan** [comment]
The code here is intended to proivides a reference implementation of the method described in our paper [AdTree: Accurate, Detailed, and Automatic Modelling of Laser-Scanned Trees](https://3d.bk.tudelft.nl/liangliang/publications/2019/adtree/AdTree_RS-2019.pdf). In principle, this code should be as clean and lightweight as possible. Thus, it seems not wise to introduce other irrelevant functionalities to this prototype implementation.
