### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by graper123** [tudelft3d/AdTree#29]
Hello Professor Nan:
I recently encountered the following error when importing Adtree into vs2022: Could not find Boost (missing: Boost - INCLUDE-DIR). How can I resolve this issue? Thank you, Teacher Nan!

**Comment by LiangliangNan** [comment]
You need to have boost installed in your system, and make sure it is visible to CMake or visual studio.
In case it still cannot be found, you will need to provide the actual path to Boost_INCLUDE_DIR when configuring the project.

I am going to close this issue becasue this is not AdTree specific, but one about using of CMake and Visual studio.

**Comment by graper123** [comment]
The issue has been resolved, and I feel like Teacher Nan's response!
