### ISSUE TITLE
There is no windows executable ?

### ISSUE THREAD

**Issue by davodogster** [tudelft3d/adtree#5]
![image](https://user-images.githubusercontent.com/46079516/112930827-7f6e4180-9177-11eb-854f-00246494957d.png)

**Comment by LiangliangNan** [comment]
You're right!
I had a windows PC but it was not accessible at the moment :-(   Will add it when possible.
If you're using windows, you can build it from its source code. 

I'd appreciate it if anyone can share their binary files :-)

**Comment by davodogster** [comment]
@LiangliangNan I was able to build it from Source on Windows Visual Studio 2019, only in debug mode - I don't know how to get it to build/run in Release Mode. The App runs and produces a skeleton for the small test data, export skeleton causes it to crash, and it's super slow and stops responding for medium size files. Import data works well for any file size.

**Comment by davodogster** [comment]
@LiangliangNan So It's working well! the problem is that It alters the Co-ordinates when I export (save) and shifts the X and Y values so when I compare it to the raw point cloud they don't align/overlap.

**Comment by LiangliangNan** [comment]
please grab the latest code and it should work now.
let me know if any issues.

**Comment by LiangliangNan** [comment]
@davodogster Could you please let me know if the issue is still there with the updated code?

**Comment by davodogster** [comment]
Hi I’m on holiday. Will try it in a few days time.
So this new commit will fix the X and Y coordinates problem so that it can align with the raw data?

I was able to compile in the previous version and generate the application exe file :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LiangliangNan** [comment]
Yes. The exported model now should align with the input points.
Enjoy your holidy!
