### ISSUE TITLE
void TreeViewer::export_skeleton() 

### ISSUE THREAD

**Issue by lsx1980** [tudelft3d/AdTree#6]
hi, the software was very good for extracting skeleton from point cloud. 
Is there anyway to export the skeleton result?

The void TreeViewer::export_skeleton() ,  const std::string& initial_name = file_system::base_name(cloud()->name()) + "_skeleton.ply"
only return and write a down sampled point cloud, is it possible to get a connected graph output?

**Comment by LiangliangNan** [comment]
It is already a graph representing the skeletons in PLY format. No?
If you look at the header (first few lines) of the PLY file) you will see the edges of the graph.

My Easy3D has an viewer for visualizing graphs.

**Comment by LiangliangNan** [comment]
I believe the issue has been solved and thus I am closing it.
You can re-open it if there are still any problems.
