### ISSUE TITLE
Output list of cylinder fits with cylinder dimensions and connectivity

### ISSUE THREAD

**Issue by achmurzy** [tudelft3d/AdTree#7]
Hello, I am interested in analyzing the fine-scale structure of tree branches with your application. However, there is no way to extract individual cylinders from the output model. All of the cylinders are fused together as a giant mesh. Is there a way to break apart the mesh, or add a flag to export all the cylinders in a row-based format like .csv? Thanks in advance, the outputs of your application are impressive and I'm interested in analyzing trees using it

**Comment by achmurzy** [comment]
It looks like I would want to save the output of 
https://github.com/tudelft3d/AdTree/blob/0ae39cb733d30b52c1a037a8039b86a5080a5dde/AdTree/skeleton.cpp#L319

rather than moving on to smooth the cylinders into a mesh in 
https://github.com/tudelft3d/AdTree/blob/0ae39cb733d30b52c1a037a8039b86a5080a5dde/AdTree/skeleton.cpp#L197

Do you think this would be easy to do? Thanks for listening

**Comment by LiangliangNan** [comment]
<img width="679" alt="Screenshot 2021-05-25 at 23 22 35" src="https://user-images.githubusercontent.com/15526536/119570204-18a08980-bdb0-11eb-85f4-0c90327e0e3f.png">
It is here (see the above figure).
You can obtain either the initial skeleton or the smoothed skeleton, all represented as a graph.
Implement your export function there to replace the current one.

**Comment by achmurzy** [comment]
Ok, so only the graph-based formats are available right now and I'll have to parse the Graph into a list of cylinders instead of writing it to a .ply mesh. Are you aware if Boost or Easy3D might have an easy way to output a Graph in a row-based file format like .csv? Thank you

**Comment by LiangliangNan** [comment]
The edges of the current graph (in PLY format) already stores the two endpoints (by the indices of the two vertices) of all the cylinders.

**Comment by achmurzy** [comment]
I will work on this and initiate a pull request if it is working and useful. Thank you again

**Comment by LiangliangNan** [comment]
The issue has been solved so I am going to close it.
Good luck!
