### ISSUE TITLE
Error in density calculation. 

### ISSUE THREAD

**Issue by harry1576** [tudelft3d/AdTree#8]
In skeleton.cpp on line 837:

`dendiff = abs(currentDensity - ptDensity);`

Shouldn't this be:

`dendiff += abs(currentDensity - ptDensity);`

As with the current implementation you are only look at the density of the point last iterated in the loop, rather than the neighborhood average?
Or is my understanding of the code wrong?

Cheers,
Harry

**Comment by LiangliangNan** [comment]
It is very likely to be an error. We will investigate it and get back to you later. 
Thanks!

**Comment by LiangliangNan** [comment]
@harry1576 Indeed, it was an error. We have fixed it and the code has been updated.
Thank you again for reporting this error!
