### ISSUE TITLE
Prebuilt executables for windows  

### ISSUE THREAD

**Issue by carlos-alberto-silva** [tudelft3d/AdTree#9]
Are there any prebuilt executables for windows? I don't see it. Thanks

**Comment by LiangliangNan** [comment]
I don't have a Windows machine, but it should be quite easy to build AdTree on Windows.

@shenglandu Can you build it on Windows and add the binaries to the [current release](https://github.com/tudelft3d/AdTree/releases/tag/v1.1.0)?

**Comment by LiangliangNan** [comment]
@carlos-alberto-silva 
Today I have access to Windows, and the binary files for Windows are built. You can down load it here:
https://github.com/tudelft3d/AdTree/releases/tag/v1.1.0

I am going to close this issue. Feel free to reopen it if you encounter any issues using the executable program.
